init:
- appveyor version
- git --version

assembly_info:
  patch: true

build_script:
- msbuild MySimpleApp.sln /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

artifacts:
  - path: '**\*.msi'
    name: MyApp
